---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sharded-redis
  namespace: ops
spec:
  serviceName: redis-service
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis
        ports:
        - name: redis
          containerPort: 6379
