---
apiVersion: v1
kind: Service
metadata:
  name: twemproxy-service
  namespace: ops
spec:
  type: ClusterIP
  selector:
    app: twemproxy
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
