---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: ops
spec:
  type: ClusterIP
  selector:
    app: twemproxy
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
