---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-core-prefix
  namespace: ops
spec:
  stripPrefix:
    prefixes:
      - /core

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: core-ingress
  namespace: ops
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: PathPrefix(`/core`)
    services:
    - name: core-service
      port: 8000
    middlewares:
      - name: strip-core-prefix
