---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: ops
spec:
  type: NodePort
  selector:
    app: core
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32767

