---
apiVersion: v1
kind: Service
metadata:
  name: sharded-redis-service
  namespace: ops
spec:
  clusterIP: None
  selector:
    app: sharded-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
