---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twemproxy-deployment
  namespace: ops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: twemproxy
  template:
    metadata:
      labels:
        app: twemproxy
    spec:
      containers:
      - name: twemproxy
        image: ganomede/twemproxy
        command:
        - "nutcracker"
        - "-c"
        - "/etc/config/twemproxy.yaml"
        - "-v"
        - "7"
        - "-s"
        - "6222"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: twemconfig
